# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: debaade1309bdc048030c3dbece3d35e7a5f709a509216fc68bb29e850dce7ac11c79acfe7d4a5de4248a39a44ea31f2d6b3c255dd36e1b9b705989db31f8100

test:
  secret_key_base: f32ad2da37986a70a9aa95587908b1595d9b7ac0c7b5c38cd8b1a176e57324befa59d9850e93d08c07f48641bae8dcc8522111c5abb780f797fd508c8cd9d19d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
